const valor = Number(window.prompt('Digite um Número'))
const valor1 = Math.sqrt(valor)
const valor2 = Number.isInteger(valor)
const valor3 = Number.isNaN(valor)
const valor4 = Math.floor(valor)
const valor5 = Math.ceil(valor)
const valor6 = valor.toFixed([2])

document.write(`Seu número é ${valor} <br>`)
document.write(`Raiz Quadrada: ${valor1}<br>`)
document.write(`Número é inteiro? ${valor2}<br>`)
document.write(`É NaN: ${valor3}<br>`)
document.write(`Arredondar para baixo ${valor4}<br>`)
document.write(`Arredondar para cima ${valor5}<br>`)
document.write(`Com dois decimais ${valor6}<br>`)